### ISSUE TITLE
"test_get_concepts_language" only fails on travis

### ISSUE THREAD

**Issue by dieuska** [koenedaele/pyramid_skosprovider#13]
@pytest.mark.xfail
   def test_get_concepts_language(self):

**Comment by dieuska** [comment]
this tests is succesfull on tox but fails on all environments on travis.
My first opinion: it is someting with request.locale_name, but after printing these values, I don'nt see a problem...strange...

**Comment by koenedaele** [comment]
Problem's been fixed. Was indeed a Travis install issue (Travis did not use the requirements.txt file).
